import { Match, Team } from '@/types/cricket';

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team_muzaffarpur',
    name: 'Muzaffarpur XI',
    shortName: 'MUZ',
    color: '#16a34a',
    createdAt: Date.now() - 86400000 * 5,
    players: [
      { id: 'muz_1', name: 'Rahul Kumar', role: 'batsman', isCaptain: true },
      { id: 'muz_2', name: 'Aman Kumar', role: 'batsman' },
      { id: 'muz_3', name: 'Rohit Singh', role: 'batsman' },
      { id: 'muz_4', name: 'Vikas Kumar', role: 'all_rounder' },
      { id: 'muz_5', name: 'Amit Kumar', role: 'wicketkeeper', isWicketkeeper: true },
      { id: 'muz_6', name: 'Deepak Sharma', role: 'all_rounder' },
      { id: 'muz_7', name: 'Sanjay Mishra', role: 'bowler' },
      { id: 'muz_8', name: 'Pooja Verma', role: 'bowler' },
      { id: 'muz_9', name: 'Ankit Raj', role: 'bowler' },
      { id: 'muz_10', name: 'Suraj Patel', role: 'bowler' },
      { id: 'muz_11', name: 'Manish Pandey', role: 'bowler' },
      { id: 'muz_12', name: 'Ravi Teja', role: 'batsman' },
    ],
  },
  {
    id: 'team_patna',
    name: 'Patna XI',
    shortName: 'PAT',
    color: '#2563eb',
    createdAt: Date.now() - 86400000 * 4,
    players: [
      { id: 'pat_1', name: 'Prakash Jha', role: 'batsman', isCaptain: true },
      { id: 'pat_2', name: 'Alok Nath', role: 'batsman' },
      { id: 'pat_3', name: 'Sunil Yadav', role: 'all_rounder' },
      { id: 'pat_4', name: 'Karan Thapa', role: 'batsman' },
      { id: 'pat_5', name: 'Abhishek Roy', role: 'wicketkeeper', isWicketkeeper: true },
      { id: 'pat_6', name: 'Md. Tariq', role: 'all_rounder' },
      { id: 'pat_7', name: 'Naveen Choudhary', role: 'bowler' },
      { id: 'pat_8', name: 'Gaurav Gill', role: 'bowler' },
      { id: 'pat_9', name: 'Pankaj Tripathi', role: 'bowler' },
      { id: 'pat_10', name: 'Dharmendra Sahu', role: 'bowler' },
      { id: 'pat_11', name: 'Vinod Kambli', role: 'bowler' },
      { id: 'pat_12', name: 'Ashok Leyland', role: 'batsman' },
    ],
  },
  {
    id: 'team_delhi',
    name: 'Delhi Challengers',
    shortName: 'DC',
    color: '#dc2626',
    createdAt: Date.now() - 86400000 * 3,
    players: [
      { id: 'del_1', name: 'Shikhar Dhawan', role: 'batsman', isCaptain: true },
      { id: 'del_2', name: 'Prithvi Shaw', role: 'batsman' },
      { id: 'del_3', name: 'Rishabh Pant', role: 'wicketkeeper', isWicketkeeper: true },
      { id: 'del_4', name: 'Axar Patel', role: 'all_rounder' },
      { id: 'del_5', name: 'Kuldeep Yadav', role: 'bowler' },
      { id: 'del_6', name: 'Ishant Sharma', role: 'bowler' },
      { id: 'del_7', name: 'Khaleel Ahmed', role: 'bowler' },
      { id: 'del_8', name: 'Lalit Yadav', role: 'all_rounder' },
      { id: 'del_9', name: 'Anrich Nortje', role: 'bowler' },
      { id: 'del_10', name: 'Mitchell Marsh', role: 'all_rounder' },
      { id: 'del_11', name: 'David Warner', role: 'batsman' },
    ],
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'match_sample_1',
    team1Id: 'team_muzaffarpur',
    team2Id: 'team_patna',
    team1PlayingXI: [
      'muz_1', 'muz_2', 'muz_3', 'muz_4', 'muz_5',
      'muz_6', 'muz_7', 'muz_8', 'muz_9', 'muz_10', 'muz_11'
    ],
    team2PlayingXI: [
      'pat_1', 'pat_2', 'pat_3', 'pat_4', 'pat_5',
      'pat_6', 'pat_7', 'pat_8', 'pat_9', 'pat_10', 'pat_11'
    ],
    format: 'T20',
    overs: 20,
    venue: 'Gandhi Maidan, Patna',
    date: new Date().toISOString().split('T')[0],
    tossWinnerId: 'team_muzaffarpur',
    tossDecision: 'bat',
    status: 'innings1',
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 300000,
    innings1: {
      teamBattingId: 'team_muzaffarpur',
      teamBowlingId: 'team_patna',
      currentStrikerId: 'muz_1',
      currentNonStrikerId: 'muz_2',
      currentBowlerId: 'pat_7',
      isCompleted: false,
      deliveries: [
        // Over 0 (bowler pat_7): 1, 0, 4, 1, 2, 0 -> 8 runs, 0 wkts
        { id: 'd_1', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 0, ballInOver: 1, strikerId: 'muz_1', nonStrikerId: 'muz_2', bowlerId: 'pat_7', runsBat: 1, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2500000 },
        { id: 'd_2', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 0, ballInOver: 2, strikerId: 'muz_2', nonStrikerId: 'muz_1', bowlerId: 'pat_7', runsBat: 0, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2450000 },
        { id: 'd_3', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 0, ballInOver: 3, strikerId: 'muz_2', nonStrikerId: 'muz_1', bowlerId: 'pat_7', runsBat: 4, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2400000 },
        { id: 'd_4', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 0, ballInOver: 4, strikerId: 'muz_2', nonStrikerId: 'muz_1', bowlerId: 'pat_7', runsBat: 1, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2350000 },
        { id: 'd_5', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 0, ballInOver: 5, strikerId: 'muz_1', nonStrikerId: 'muz_2', bowlerId: 'pat_7', runsBat: 2, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2300000 },
        { id: 'd_6', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 0, ballInOver: 6, strikerId: 'muz_1', nonStrikerId: 'muz_2', bowlerId: 'pat_7', runsBat: 0, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2250000 },
        // Over 1 (bowler pat_8): 0, 6, 1, 0, Wicket (Aman caught), 1 -> 8 runs, 1 wkt
        { id: 'd_7', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 1, ballInOver: 1, strikerId: 'muz_2', nonStrikerId: 'muz_1', bowlerId: 'pat_8', runsBat: 0, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2200000 },
        { id: 'd_8', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 1, ballInOver: 2, strikerId: 'muz_2', nonStrikerId: 'muz_1', bowlerId: 'pat_8', runsBat: 6, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2150000 },
        { id: 'd_9', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 1, ballInOver: 3, strikerId: 'muz_2', nonStrikerId: 'muz_1', bowlerId: 'pat_8', runsBat: 1, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2100000 },
        { id: 'd_10', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 1, ballInOver: 4, strikerId: 'muz_1', nonStrikerId: 'muz_2', bowlerId: 'pat_8', runsBat: 0, extraRuns: 0, isLegal: true, timestamp: Date.now() - 2050000 },
        {
          id: 'd_11',
          matchId: 'match_sample_1',
          inningsIndex: 1,
          overIndex: 1,
          ballInOver: 5,
          strikerId: 'muz_1',
          nonStrikerId: 'muz_2',
          bowlerId: 'pat_8',
          runsBat: 0,
          extraRuns: 0,
          isLegal: true,
          wicket: { playerOutId: 'muz_1', wicketType: 'caught', bowlerId: 'pat_8', fielderId: 'pat_1' },
          timestamp: Date.now() - 2000000,
        },
        { id: 'd_12', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 1, ballInOver: 6, strikerId: 'muz_3', nonStrikerId: 'muz_2', bowlerId: 'pat_8', runsBat: 1, extraRuns: 0, isLegal: true, timestamp: Date.now() - 1950000 },
        // Over 2 (bowler pat_7): Wide, 4, 1, 2
        { id: 'd_13', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 2, ballInOver: 1, strikerId: 'muz_3', nonStrikerId: 'muz_2', bowlerId: 'pat_7', runsBat: 0, extraRuns: 1, extraType: 'wide', isLegal: false, timestamp: Date.now() - 1800000 },
        { id: 'd_14', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 2, ballInOver: 1, strikerId: 'muz_3', nonStrikerId: 'muz_2', bowlerId: 'pat_7', runsBat: 4, extraRuns: 0, isLegal: true, timestamp: Date.now() - 1750000 },
        { id: 'd_15', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 2, ballInOver: 2, strikerId: 'muz_3', nonStrikerId: 'muz_2', bowlerId: 'pat_7', runsBat: 1, extraRuns: 0, isLegal: true, timestamp: Date.now() - 1700000 },
        { id: 'd_16', matchId: 'match_sample_1', inningsIndex: 1, overIndex: 2, ballInOver: 3, strikerId: 'muz_2', nonStrikerId: 'muz_3', bowlerId: 'pat_7', runsBat: 2, extraRuns: 0, isLegal: true, timestamp: Date.now() - 1650000 },
      ],
    },
  },
];
